Ayushjhawar8/Flavor-ai

README.md
This pull request improves the readability and user experience of the README.md by adding a small, centered "🔝 Back to Top" button after major sections.
Changes Made:
Added a <kbd>🔝 Back to Top</kbd> HTML anchor to relevant sections
Ensured consistent formatting and centered alignment
=> Add "Back to Top" Button for Easier Navigation in README

app/page.jsx
🔗 Related Issue:
closes  #13 
Improved the UI/UX of the cards by adding shadow and hover.
=> Improved UI/UX of cards

app/globals.css
Changed the background color of the `body` element using Tailwind CSS utility classes. The new styles apply a gradient background from `indigo-50` to `blue-100` in a bottom-right direction:
```css
body {
@apply bg-gradient-to-br from-indigo-50 to-blue-100;
}
```
This enhances the page with a soft, modern gradient for improved visual appearance.
Closes #58
**After:**
=> Changed the background color of body and attached screenshot shows some visible dark color

app/page.jsx, components/RecipeSearchBar.jsx
- Improved mobile UX by adjusting navbar layout:
- Placed FlavorAI logo and GitHub icon on the left
- Moved the Search Bar to the right
Closes #51 
- Before 
- After
=> Improved mobile navbar styling

app/page.jsx
Added a "Contribute on GitHub" button to the project footer.
The button links directly to the GitHub issues page to encourage open-source contributions and make it easier for users to explore issues.
Closes #41  
Before:
After:
=> Contribute on GitHub button in footer linking to project issues

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md
Please describe your changes and what this PR addresses.
I have added an issue template
Closes #77 
(Add before/after screenshots if your change is visual)
=> Added issue template

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/chore_request.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
This PR adds standardized issue templates to improve the contribution workflow and ensure consistency across reported issues and requests.
- 🐞 Bug Report
- 🚀 Feature Request
- 🧹 Chore Task
- 📚 Documentation Update
- ❓ General Question / Help
Each template includes pre-defined labels and structured prompts to help contributors provide clear, actionable information.
Once merged into the default branch, these templates will automatically appear when someone clicks "New Issue" in the repository. Users will be able to select the issue type, fill out the guided form, and the appropriate label will be applied automatically.
This makes the process more efficient for both contributors and maintainers.
=> [FEAT]: add issue tempaltes, bug, chore, documentation, feat and question

app/api/generate-recipe/route.js
Contributor ID : 10049d93-7440-4ac4-806c-ad3b1202a10c
The old prompt was a bit vague, so sometimes the AI would give weird or incomplete recipes.
With this change, the AI will give us recipes that are:
Consistent and always follow the same structure.
Easier for users to read and follow.
More likely to respect dietary needs and personal requests.
Just generally more useful and fun!
I’ve rewritten the system prompt that tells the AI how to generate recipes.
The new prompt is much clearer and more detailed. It now:
Tells the AI to act like a professional chef.
Asks for a recipe in a specific, easy-to-read JSON format.
Makes sure dietary restrictions and user preferences are front and center.
Requests a short, one-line description for every recipe.
Encourages the use of simple, common …
=> promt refined

components/RecipeSearchBar.jsx
Implemented debouncing on the search input to reduce excessive API calls.
Closes #90 
before 
https://github.com/user-attachments/assets/f8772141-d153-46cd-a346-44dd84e75542
after
https://github.com/user-attachments/assets/0e40d3f4-1f12-430e-9a02-0e09ed31be42
=> improve-search

.env.sample, README.md, app/api/generate-diet-plan/route.js, app/api/test-diet-plan/route.js, app/diet-planner/page.jsx, app/page.jsx, lib/diet-planner.test.js, lib/schemas.js
- Add comprehensive AI diet planner feature using Groq API
- Implement health-conscious meal planning based on user profile
- Support blood sugar and blood pressure considerations
- Include BMR/TDEE calculations for accurate calorie targets
- Add fitness goal alignment (bulk, cut, maintain, general health)
- Support dietary restrictions and allergy considerations
- Create responsive UI with detailed nutritional information
- Add test API endpoint for development and demonstration
- Include comprehensive meal recipes with cooking instructions
- Provide health notes and exercise recommendations
- Update navigation with diet planner access
- Add schema validation for structured diet plans
- Include test suite for validation and calculations
Please describe your changes and what this PR …
=> feat: Add AI Diet Planner with personalized meal plans

app/category/[category]/page.tsx, app/favorite/page.tsx, components/Footer.jsx, components/ShowMeal.jsx
I have fixed issue of font color not visible in dark mode theme in 3 files:
1. Footer.jsx (applied similar logic as navbar & body for dark mode to track mode changes)
2. ShowMeal.jsx (replaced tailwind class with daisyUI semantic color classes that automatically adapt color based on light/dark mode)
3. category/page.tsx 
Closes #152 
Before:
After:
- [✅] My code compiles without errors
- [✅] I have tested my changes
=> Fixed Font colors not visible on dark theme

app/api/calculate-recipe-cost/route.js, app/api/grocery-prices/route.js, app/globals.css, app/page.jsx, components/BudgetPlanner.jsx, components/CostCalculator.jsx, components/Navbar.tsx, components/ShowMeal.jsx, docs/RECIPE_COST_CALCULATOR.md, lib/RecipeContext.js, lib/costCalculator.js, lib/costCalculator.test.js, lib/groceryPrices.js, lib/pricingService.js, lib/recipeService.js
This PR implements a comprehensive Recipe Cost Calculator feature that helps users estimate ingredient costs directly within recipe pages. Instead of redirecting users to a separate calculator page, the cost calculator is now seamlessly integrated into the recipe display, providing immediate cost visibility and better user experience.
- **Removed separate cost calculator page** (`app/cost-calculator/page.jsx`) to eliminate broken redirects
- **Integrated cost calculator directly into ShowMeal component** for immediate cost visibility
- **Added comprehensive cost breakdown** including ingredient costs, total recipe cost, and savings comparison
- **Removed navigation links** to cost calculator from main page and navbar to prevent confusion
- **Implemented inline cost calculation** with …
=> Recipe Cost Calculator

app/page.jsx, components/ShowMeal.jsx
Please describe your changes and what this PR addresses.
Do let me know if I made some error or if I need to change something! 
This closes [#129](https://github.com/Ayushjhawar8/Flavor-ai/issues/129)
The before images:
And the after images:
- [✅] My code compiles without errors
- [✅] I have tested my changes
=> Added allergen info underneath the cuisine and added diet-based tag filtering

app/ai/page.jsx, app/globals.css, app/layout.jsx, components/SnakeCursor.tsx, package-lock.json, package.json
This PR introduces a playful snake-style trail that follows the user's cursor. It adds a smooth, animated effect to mouse movement, making the UI feel more dynamic and engaging. Great for boosting interactivity and visual appeal!
Closes : #172
before : 
After : 
https://github.com/user-attachments/assets/32d03d06-b6e5-4cc4-825a-a621e882bbe1
=> [ FEAT ]: Added a "Cursor Trail Effect " 

.gitignore, app/api/recipes/[id]/comments/route.js, app/meal/[meal]/page.jsx, components/RecipeComments.jsx, lib/comments.js, lib/schemas.js
1)Add Comment Schema to lib/schema.js
2) Create Comment Storage System
3) Add to .gitignore
4) Create Data Directory
Create: app/api/recipes/[id]/comments/route.js
Create a new file: components/RecipeComments.jsx
modify the app/meal/[meal]/page.jsx file to include the RecipeComments component.
✅ Core Functionality Tests
1)Rate Limiting Test:
Try posting another comment immediately after your first one
You should get an error: "Please wait before posting another comment"
2)CAPTCHA Validation:
Try submitting with wrong math answer
Should show error and regenerate the math problem
3)Comment Validation:
Try posting a comment with less than 10 characters
Try posting a comment with more than 500 characters
Both should show validation errors
4)Content Filtering:
Try posting a comment with the …
=> Add: anonymous comment section

components/ShowMeal.jsx
This PR introduces two key enhancements:
- **Ingredient text highlighting**: Implemented highlighting behavior for ingredients, consistent with the existing step highlighting.  
- **Independent TTS control**: Decoupled text-to-speech functionality for ingredients and steps, allowing them to run without interfering with each other.  
---
Closes #220  
---
https://github.com/user-attachments/assets/2ebb7dad-ac60-4067-ba83-66863a43e594
---
=> [FEAT] Highlight Ingredient text

components/Navbar.tsx
This PR introduces changes to the Nav Bar by adding a new "Home" button that redirects to the home page when clicked. The changes improve both accessibility and user experience.
Styled the Home button with:
1. Responsive size and padding
2. Backdrop blur and transparency
3. Dark and light mode compatibility
4. Interactive hover effects: scale-up and shadow
Closes #223 
Screenshot of Home Tab:
Clicking on this Home button redirects back to the Home Page of the website instantly.
Screenshot after redirecting:
1. Quick navigation back to homepage
2. Easier theme switching with a prominent toggle
3. Accessibility improvements through aria-label
Kindly review and merge the PR @Ayushjhawar8
=> Added a Home Button on the navbar that redirects back to the home page

app/diet-planner/page.jsx
1. This PR adds a Diet Preference dropdown field to the Diet Planner form, addressing the need for more personalized meal planning.
2. A new dropdown has been added just above “Dietary Restrictions” for logical flow.
3. Options included: Vegetarian, Non-Vegetarian, Eggetarian, Vegan.
4. The selected value is stored in formData state.
5. The backend request payload is updated to include dietPreference, ensuring meal plan generation respects the user’s dietary preference.
6. Improves overall user experience by filtering dishes more accurately and avoiding irrelevant suggestions
Closes #222
=> Add Diet Preference Dropdown (Vegetarian, Non-Vegetarian, Eggetarian, Vegan) to Diet Planner Form with Vegetarian toggle on the top

app/ai/page.jsx, app/category/[category]/page.tsx, app/diet-planner/page.jsx, app/favorite/page.tsx, components/Navbar.tsx, components/ShowMeal.jsx, package-lock.json
Fixed search bar consistency issues across the entire Flavor AI application. The search bar now behaves uniformly on all pages with proper background blur effects and smooth transitions.
Added missing search state management to AI, category, meal, and other pages
Implemented consistent background blur effect when search is active
Added smooth transitions for polished user experience
Made Navbar props optional for backward compatibility
Ensured search functionality works properly on every page
Closes #236 
**HomePage**
**Before:**
**After:**
**Ai page**
**Before**
**After:**
**RandomPage:**
**Before:**
**After:**
**DietPlanner Page:**
**Before:**
**After:**
**Favourites Page:**
**Before:**
**After:**
- [✅] My code compiles without errors
- [✅] I have tested my changes
=> Fix: Blur the background & search functionality consistently across all pages

app/diet-planner/page.jsx
This pull request updates the Diet Planner form (app/diet-planner/page.jsx) to include more inclusive gender options.
Previously, the gender dropdown only supported:
1) Male
2) Female
With this change, the following options are now available:
1) Male
2) Female
3) Other
4) Prefer not to say
Closes #224 
Before:-
After:-
=> Added more gender options (Other, Prefer not to say) in diet planner
